version: "3"
services:
  node:
    image: pedroquessada/my-backend:latest
    build: .
    command: "npm run start"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3000:3000"