apiVersion: v1
kind: Pod
metadata:
  name: my-backend
spec:
  containers:
  - name: my-backend
    image: pedroquessada/my-backend:latest
    imagePullPolicy: Never
    workingDir: /usr/api
    resources:
      requests:
        memory: "400Mi"
        cpu: "500m"
      limits:
        memory: "400Mi"
        cpu: "500m"
    ports:
    - containerPort: 3000