name: Create aws resource using terraform
env:
  CI: ""
on:
  workflow_dispatch:
    inputs:
      region:
        description: ''
        required: true
        default: 'us-east-1'
      prefix:
          description: ''
          required: true
          default: 'backend'
      repository_name:
        description: ''
        required: true
        default: 'backend'
      cluster_name:
          description: ''
          required: true
          default: 'backend'

jobs:
  apply:
    name: 'terraform apply'
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.region }}
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.6.1    

      - name: Terraform init
        working-directory: infra/
        run: | 
          terraform init
      
      - name: Define terraform vars
        working-directory: infra/
        run: |
          echo "access_key = \"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> terraform.tfvars
          echo "secret_key = \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> terraform.tfvars
          echo "session_token = \"${{ secrets.AWS_SESSION_TOKEN }}\"" >> terraform.tfvars
          echo "user_id = \"${{ secrets.AWS_USER_ID }}\"" >> terraform.tfvars
          echo "region = \"${{ github.event.inputs.region }}\"" >> terraform.tfvars
          echo "prefix = \"${{ github.event.inputs.prefix }}\"" >> terraform.tfvars
          echo "repository_name = \"${{ github.event.inputs.repository_name }}\"" >> terraform.tfvars
          echo "cluster_name = \"${{ github.event.inputs.cluster_name }}\"" >> terraform.tfvars

      # - name: Create infra using terraform
      #   working-directory: infra/
      #   run: | 
      #     terraform apply -auto-approve -var-file=terraform.tfvars

      # - name: AWS ECR
      #   run: |
      #     aws ecr get-login-password --region ${{ github.event.inputs.region }} | docker login --username AWS --password-stdin ${{ secrets.AWS_USER_ID }}.dkr.ecr.${{ github.event.inputs.region }}.amazonaws.com
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Publish docker image on ERS
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t ECR_REGISTRY/${{ github.event.inputs.repository_name }} .
          docker push ECR_REGISTRY/${{ github.event.inputs.repository_name }}
      
      - name: Deploy application to EKS using terraform
        working-directory: infra/application
        run: |
          terraform init
          terraform apply -auto-approve -var-file=../terraform.tfvars