name: Create aws resource using terraform

on:
  workflow_dispatch:
    inputs:
      region:
        description: ''
        required: true
        default: 'us-east-1'
      prefix:
          description: ''
          required: true
          default: 'backend'
      repository_name:
        description: ''
        required: true
        default: 'backend'
      cluster_name:
          description: ''
          required: true
          default: 'backend'
      image:
        description: ''
        required: true
        default: 'pedroquessada/my-backend:latest'
      role:
          description: ''
          required: true
          default: 'arn:aws:iam::211125361403:role/LabRole'

jobs:
  apply:
    name: 'terraform apply'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

      - name: Setup AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.1    
      
      - name: Update terraform.tfvars
        run: |
          echo "region = \"${{ github.event.inputs.region }}\"" >> ./infra/terraform.tfvars
          echo "prefix = \"${{ github.event.inputs.prefix }}\"" >> ./infra/terraform.tfvars
          echo "repository_name = \"${{ github.event.inputs.repository_name }}\"" >> ./infra/terraform.tfvars
          echo "cluster_name = \"${{ github.event.inputs.cluster_name }}\"" >> ./infra/terraform.tfvars
          echo "image = \"${{ github.event.inputs.image }}\"" >> ./infra/terraform.tfvars
          echo "role = \"${{ github.event.inputs.role }}\"" >> ./infra/terraform.tfvars

      - name: Terraform init
        run: | 
          terraform init

      - name: Debug
        run: | 
          ls -l
          cat ./infra/terraform.tfvars

      - name: Terraform plan
        run: | 
          terraform plan -var-file=./infra/terraform.tfvars --auto-approve