name: Create aws resource using terraform
env:
  CI: ""
on:
  # push:
  #   branches: ["master"]
  workflow_dispatch:
    inputs:
      region:
        description: ''
        required: true
        default: 'us-east-1'
      prefix:
          description: ''
          required: true
          default: 'backend'
      repository_name:
        description: ''
        required: true
        default: 'backend'
      cluster_name:
          description: ''
          required: true
          default: 'backend'

jobs:
  apply:
    name: 'Deploy app'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.region }}
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.6.1    
      
      - name: Define terraform vars
        working-directory: infra/application
        run: |
          echo "access_key = \"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> terraform.tfvars
          echo "secret_key = \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> terraform.tfvars
          echo "session_token = \"${{ secrets.AWS_SESSION_TOKEN }}\"" >> terraform.tfvars
          echo "prefix = \"${{ secrets.PREFIX }}\"" >> terraform.tfvars
          echo "repository_name = \"${{ secrets.REPOSITORY_NAME }}\"" >> terraform.tfvars

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.AWS_USER_ID }}
          mask-password: "true" # see: https://github.com/aws-actions/amazon-ecr-login#docker-credentials
      
      - name: Publish docker image on ERS
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.REPOSITORY_NAME }} .
          docker push $ECR_REGISTRY/${{ secrets.REPOSITORY_NAME }}
      
      # - name: Deploy application to EKS using terraform
      #   working-directory: infra/application
      #   run: |
      #     terraform init
      #     terraform apply -auto-approve -var-file=../terraform.tfvars