name: Create GCP resources using terraform
env:
  CI: ""
on:
  workflow_dispatch:

jobs:
  apply:
    name: 'terraform apply'
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.6.1    
      
      - name: Define terraform vars
        working-directory: terraform/gcp/create-gcp-infra
        run: |
          echo "image_version = \"${{ github.run_id }}\"" >> terraform.tfvars
          echo "region = \"${{ vars.REGION }}\"" >> terraform.tfvars
          echo "zone = \"${{ vars.ZONE }}\"" >> terraform.tfvars
          echo "prefix = \"${{ vars.PREFIX }}\"" >> terraform.tfvars
          echo "project_id = \"${{ vars.PROJECT_ID }}\"" >> terraform.tfvars
          echo "bucket_name = \"${{ vars.BUCKET }}\"" >> terraform.tfvars

      # - name: Enable GCP services
      #   working-directory: terraform/gcp/enable-services
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      #   run: | 
      #     terraform init \
      #     -backend-config="bucket=${{ vars.BUCKET }}" \
      #     -backend-config="prefix=terraform/state/services"
      #     terraform apply -auto-approve -var="project_id=${{ vars.PROJECT_ID }}" -var="region=${{ vars.REGION }}" -var="zone=${{ vars.ZONE }}" 

      - name: Create infra using terraform
        working-directory: terraform/gcp/create-gcp-infra
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: | 
          terraform init \
          -backend-config="bucket=${{ vars.BUCKET }}" \
          -backend-config="prefix=terraform/state/infra"
          terraform apply -auto-approve -var-file=terraform.tfvars   