name: Deploy application to GCP-GKE
env:
  CI: ""
on:
  # push:
  #   branches: ["main", "master"]
  workflow_dispatch:

jobs:
  apply:
    name: 'Deploy app'
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      # Auth gcloud to gke --> gcloud container clusters get-credentials teste-416204-gke --region=us-central1-f
      - uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Configure Docker Client
        working-directory: app/
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet

      - name: Publish docker image on ERS2
        working-directory: app/
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          docker build -t ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/docker-images-rep/app:${{ github.run_id }} .
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/docker-images-rep/app:${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: 1.6.1    

      - name: Define terraform vars
        working-directory: terraform/gcp/deploy-app
        run: |
          echo "image_version = \"${{ github.run_id }}\"" >> terraform.tfvars
          echo "region = \"${{ vars.REGION }}\"" >> terraform.tfvars
          echo "zone = \"${{ vars.ZONE }}\"" >> terraform.tfvars
          echo "prefix = \"${{ vars.PREFIX }}\"" >> terraform.tfvars
          echo "project_id = \"${{ vars.PROJECT_ID }}\"" >> terraform.tfvars
          echo "bucket_name = \"${{ vars.BUCKET }}\"" >> terraform.tfvars

      - name: Create infra using terraform
        working-directory: terraform/gcp/deploy-app
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: | 
          terraform init \
          -backend-config="bucket=${{ vars.BUCKET }}" \
          -backend-config="prefix=terraform/state/app"
          terraform apply -auto-approve -var-file=terraform.tfvars   