name: Auto commit
env:
  CI: ""
on:
  workflow_dispatch:

jobs:
  apply:
    name: 'terraform apply'
    runs-on: ubuntu-20.04

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Test
        working-directory: terraform/create-aws-infra/
        run: |
          export S3_URI="test"
          echo "URI do S3: $S3_URI"